[general]
# gcal, caldav, ics
provider =
# calendar where upload the time table
calendar =
# Accademic year: 1, 2, 3
year =
# Array of lesson to ignore when uploding
ignore = [ 'materia1', 'materia2' ]
# true if you want to update events that already happened, false otherwise
updatePastEvents = false

[gcal]
# /path/to/token
credentials =

[caldav]
# Nextcloud, iCloud, Office365, etc..
provider =
username =
# CalDav URL
url =

[ics]
# save in the current path (true/false)
usePath =
# folder in whitch to save the file
folder =
filename =
