[general]
# gcal, caldav, etc..
provider =
# calendar where upload the time table
calendar =
# Accademic year: 1, 2, 3
year =
# Array of lesson to ignore when uploding
ignore = [ 'materia1', 'materia2' ]

[gcal]
# /path/to/token
credentials =

[caldav]
# Nextcloud, iCloud, Office365, etc..
provider =
username =
# CalDav URL
url =
