[general]
# gcal, caldav
provider =
# calendar where upload the time table
calendar =
# Array of lesson to ignore when uploding (with support for regex)
blacklist = [ 'materia1', 'materia2.*' ]
# Array of lesson to include
whitelist = [ 'materia1', 'materia2.*' ]
# true if you want to update events that already happened, false otherwise
updatePastEvents = false
# Course code, it can be found between square brackets here -> https://www.unive.it/data/8321/
# eg. for "Informatica" it would be "CTR3"
courseCode = 


[gcal]
# /path/to/token
credentials =

[caldav]
# Nextcloud, iCloud, Office365, etc..
provider =
username =
# CalDav URL
url =

[ics]
# save in the current path (true/false)
usePath =
# folder in whitch to save the file
folder =
filename =
